/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';
import { set } from 'idb-keyval';

declare const self: ServiceWorkerGlobalScope;

// Workbox: Claim clients immediately to control them without a reload
self.skipWaiting();
clientsClaim();

// Workbox: Precache assets generated by Next.js
precacheAndRoute(self.__WB_MANIFEST);

// --- Share Target Handler ---
// This listens for the POST request configured in manifest.json
self.addEventListener('fetch', (event) => {
    const url = new URL(event.request.url);

    // Matches the action in manifest.json: "action": "/share-target"
    if (event.request.method === 'POST' && url.pathname === '/share-target') {
        event.respondWith(
            (async () => {
                try {
                    // 1. Get the FormData
                    const formData = await event.request.formData();
                    const mediaFile = formData.get('file'); // "file" matches the name in manifest.json

                    if (mediaFile && mediaFile instanceof File) {
                        // 2. Save to IndexedDB so the client page can read it
                        // We use idb-keyval for simplicity
                        await set('shared-file', mediaFile);
                        console.log('[SW] Shared file saved to IDB:', mediaFile.name);
                    }

                    // 3. Redirect to the Dashboard Expenses page with a query param
                    return Response.redirect('/dashboard/expenses?shared=true', 303);

                } catch (err) {
                    console.error('[SW] Error handling share target:', err);
                    // Fallback redirect even on error
                    return Response.redirect('/dashboard/expenses', 303);
                }
            })()
        );
    }
});
