/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { set } from 'idb-keyval';

declare const self: ServiceWorkerGlobalScope;

// Workbox: Claim clients immediately to control them without a reload
self.skipWaiting();
clientsClaim();

// Workbox: Precache assets generated by Next.js
precacheAndRoute(self.__WB_MANIFEST);

// --- Share Target Handler ---
registerRoute(
    ({ url, request }) => request.method === 'POST' && url.pathname === '/share-target',
    async ({ request }) => {
        try {
            const formData = await request.formData();
            const mediaFile = formData.get('file');
            const title = formData.get('title') || '';
            const text = formData.get('text') || '';
            const url = formData.get('url') || '';

            // Combine text parts
            const description = [title, text, url].filter(v => v && typeof v === 'string').join(' ').trim();

            if (mediaFile && mediaFile instanceof File) {
                await set('shared-file', mediaFile);
            }

            const redirectUrl = new URL('/dashboard/expenses', self.location.href);
            redirectUrl.searchParams.set('shared', 'true');
            if (description) {
                redirectUrl.searchParams.set('description', encodeURIComponent(description));
            }

            return Response.redirect(redirectUrl.href, 303);
        } catch (err) {
            console.error('[SW] Error handling share target:', err);
            return Response.redirect('/dashboard/expenses', 303);
        }
    },
    'POST'
);
